import { NextResponse } from "next/server"
import path from "path"
import fs from "fs/promises"
import { readGitHubSession } from "@/lib/githubAuth"
import { pushProjectToGitHub, type FileToPush } from "@/lib/agents/githubPushService"
import { AgentExecutionError } from "@/lib/agents/shared"

export const maxDuration = 60

export async function POST(req: Request) {
    try {
        const body = await req.json()
        const {
            projectId,
            repoName,
            isPrivate = false,
            description,
            commitMessage,
            githubToken,
            files: incomingFiles,
        } = body

        // 1. Resolve GitHub Token (Connected OAuth Session > Body Token > GITHUB_PAT)
        const session = await readGitHubSession()
        const resolvedToken =
            (typeof githubToken === "string" && githubToken.trim() ? githubToken.trim() : null) ||
            session?.accessToken ||
            process.env.GITHUB_PAT

        if (!resolvedToken) {
            return NextResponse.json(
                {
                    error: "GitHub not connected. Please connect your GitHub account or provide a Personal Access Token.",
                    needsAuth: true,
                },
                { status: 401 }
            )
        }

        // 2. Gather files to push
        const filesToPush: FileToPush[] = []

        if (Array.isArray(incomingFiles) && incomingFiles.length > 0) {
            for (const f of incomingFiles) {
                if (f && typeof f.path === "string" && typeof f.content === "string") {
                    filesToPush.push({ path: f.path, content: f.content })
                }
            }
        } else if (projectId && typeof projectId === "string") {
            const safeProjectId = projectId.replace(/[^a-zA-Z0-9-_]/g, "")
            const projectDir = path.join(process.cwd(), "projects", safeProjectId)

            try {
                const dirEntries = await fs.readdir(projectDir, { withFileTypes: true })
                for (const entry of dirEntries) {
                    if (entry.isFile()) {
                        const content = await fs.readFile(path.join(projectDir, entry.name), "utf-8")
                        filesToPush.push({ path: entry.name, content })
                    }
                }
            } catch (dirErr) {
                console.warn("[push-project] Could not read project directory:", dirErr)
            }
        }

        // Ensure at least a README exists if no files were loaded
        if (filesToPush.length === 0) {
            filesToPush.push({
                path: "README.md",
                content: `# ${repoName || "WorkingGent Project"}\n\nGenerated by WorkingGent AI Agent Swarm.\n`,
            })
        }

        // 3. Push to GitHub
        const result = await pushProjectToGitHub({
            repoName,
            isPrivate: Boolean(isPrivate),
            description: description || "Created and published with WorkingGent",
            commitMessage: commitMessage || `feat: publish ${repoName || "project"} via WorkingGent`,
            files: filesToPush,
            accessToken: resolvedToken,
        })

        return NextResponse.json({
            ...result,
        })
    } catch (error: unknown) {
        console.error("[api/github/push-project] Error:", error)

        if (error instanceof AgentExecutionError) {
            return NextResponse.json(
                { error: error.message, code: error.code },
                { status: error.status }
            )
        }

        return NextResponse.json(
            { error: error instanceof Error ? error.message : "GitHub push failed." },
            { status: 500 }
        )
    }
}
